def make_features_to_highlight():

    return {
        'Pablo State': ('State', ),
#         'Mutation': (
#             'BRCA1',
#             'BRCA2',
#             'NF1',
#             'RB1',
#         ),
#         'CNV': (
#             'ANKH (GAIN)',
#             'BRCA1 (LOSS)',
#             'BRCA2 (LOSS)',
#             'CCNE1 (GAIN)',
#             'DUSP21 (LOSS)',
#             'RB1 (LOSS)',
#             'IL25 (LOSS)',
#             'HOMEZ (LOSS)',
#             'NOTCH2NL (GAIN)',
#         ),
#         'Methylation': (
#             'XRCC2',
#             'DHX37',
#             'FEZ1',
#             'GAS6',
#         ),
#         'RNA': (
#             'APC',
#             'AR',
#             'AXL',
#             'BRAF',
#             'BRCA1',
#             'CDK4',
#             'CDK6',
#             'CDKN2A',
#             'E2F1',
#             'EGFR',
#             'ERBB3',
#             'ESR1',
#             'EZH2',
#             'F2RL1',
#             'FAM200B',
#             'FAT1',
#             'FZD1',
#             'GAPDH',
#             'GPR123',
#             'GPX1',
#             'GPX8',
#             'HNF1A',
#             'HOMEZ',
#             'IKBKE',
#             'IL6',
#             'IL8',
#             'KRAS',
#             'MAP2',
#             'MAP4K4',
#             'MTOR',
#             'MYC',
#             'NF1',
#             'NOTCH1',
#             'NRAS',
#             'PGR',
#             'PIK3CA',
#             'PPP2CA',
#             'PTEN',
#             'RAD17',
#             'RELA',
#             'SOX10',
#             'ST14',
#             'TOX4',
#             'TP53',
#             'TTC23L',
#             'VIM',
#             'YAP1',
#             'ZEB1',
#         ),
#         'Gene Set C2': (
#             'AIGNER_ZEB1_TARGETS',
#             'HINATA_NFKB_TARGETS_KERATINOCYTE_UP',
#         ),
#         'Gene Set IPA Regulator': ('IPA_E2F1_UP', ),
#         'Protein': (
#             'AR',
#             'EGFR_pY1068_Caution',
#             'ER-alpha',
#             'ER-alpha_pS118',
#             'FRA1_Caution',
#             'HER2',
#             'HER2_pY1248_Caution',
#             'HER3',
#             'IGFBP2',
#             'MEK1_pS217_S221',
#             'N-Cadherin',
#             'P-Cadherin_Caution',
#             'PKC-alpha',
#             'PKC-alpha_pS657_Caution',
#             'PR',
#             'VEGFR2',
#         ),
#         'Achilles RNAi': (
#             'CDK2AP2',
#             'CDKL4',
#             'CDKN2A',
#             'CDKN2AIPNL',
#             'CDKN2D',
#             'ERBB3',
#             'ESR1',
#             'FOXA1',
#             'GAS6',
#             'GATA3',
#             'GNAS',
#             'HNF4A',
#             'IDH1',
#             'PAX8',
#             'RGS8',
#             'SOX9',
#             'UROD',
#         ),
#         'Achilles CRISPR': (
#             'CDK2AP2',
#             'CDKL4',
#             'CDKN2A',
#             'CDKN2AIPNL',
#             'CDKN2D',
#             'ERBB3',
#             'ESR1',
#             'FOXA1',
#             'GAS6',
#             'GATA3',
#             'GNAS',
#             'IDH1',
#             'PAX8',
#             'RGS8',
#             'SOX9',
#             'UROD',
#         ),
#         'CTRP Compound': (
#             '1S,3R-RSL-3',
#             'BRD-K30748066',
#             'BRD-K71935468',
#             'KW-2449',
#             'ML162',
#             'ML210',
#             'ML320',
#             'N9-isopropylolomoucine',
#             'PHA-793887',
#             'SB-525334',
#             'SNS-032',
#             'alvocidib',
#             'austocystin D',
#             'birinapant',
#             'cimetidine',
#             'decitabine',
#             'dinaciclib',
#             'elocalcitol',
#             'erastin',
#             'neratinib',
#             'obatoclax',
#             'pluripotin',
#             'saracatinib',
#             'vandetanib',
#         ),
    }
